// Code generated by goagen v1.2.0, DO NOT EDIT.
//
// API "cellar": js TestHelpers
//
// Command:
// $ goagen
// --design=project/goa-tutorial/design
// --out=$(GOPATH)/src/project/goa-tutorial
// --version=v1.2.0

package test
